### ISSUE TITLE
Categories are not unique anymore after first training

### ISSUE THREAD

**Issue by tomvanderputte** [Hapyr/trans-cat#1]
When I train a dataset, and then want to run inference on it with another dataset, it works. But when opening the list to re-assign a category when it is not correct, it gives me a lot of non-unique catagories:

![image](https://user-images.githubusercontent.com/65624141/187032342-8f1d593a-aa7b-4e47-8856-9192716cdb31.png)

and:

![image](https://user-images.githubusercontent.com/65624141/187032366-45c001af-b1c3-48cb-a3c9-635bb69cef30.png)

**Comment by Hapyr** [comment]
Thanks for reporting. Quick fix in the last commit.
